/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FORMULARIOS;
import parcial_progra2.Conexion;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
/**
 *
 **/
public class Director extends javax.swing.JFrame {
private final Director DT;
    /**
     * Creates new form Jframe_1
     */
    public Director() {
        initComponents();
        DT= new Director();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_Welcome = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        txt_ID = new javax.swing.JTextField();
        lbl_ID = new javax.swing.JLabel();
        lbl_NOMBRE = new javax.swing.JLabel();
        txt_NOMBRE = new javax.swing.JTextField();
        lbl_NIT = new javax.swing.JLabel();
        txt_NIT = new javax.swing.JTextField();
        lbl_YEAR = new javax.swing.JLabel();
        txt_YEAR = new javax.swing.JTextField();
        btn_close = new javax.swing.JButton();
        btn_agg = new javax.swing.JButton();
        txt_DPI = new javax.swing.JTextField();
        lbl_DPI = new javax.swing.JLabel();
        btnbuscar = new javax.swing.JButton();
        btn_UPDATE = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbl_Welcome.setBackground(new java.awt.Color(153, 255, 255));
        lbl_Welcome.setFont(new java.awt.Font("Lucida Bright", 1, 36)); // NOI18N
        lbl_Welcome.setText("BIENVENIDO");
        lbl_Welcome.setToolTipText("");

        jPanel1.setBackground(new java.awt.Color(102, 0, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 59, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel2.setBackground(new java.awt.Color(102, 0, 0));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 47, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        txt_ID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_IDActionPerformed(evt);
            }
        });

        lbl_ID.setText("ID:");

        lbl_NOMBRE.setText("Nombre:");

        txt_NOMBRE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_NOMBREActionPerformed(evt);
            }
        });

        lbl_NIT.setText("NIT:");

        txt_NIT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_NITActionPerformed(evt);
            }
        });

        lbl_YEAR.setText("Año de Nacimiento:");

        txt_YEAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_YEARActionPerformed(evt);
            }
        });

        btn_close.setText("SALIR");
        btn_close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_closeActionPerformed(evt);
            }
        });

        btn_agg.setText("AGREGAR");
        btn_agg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_aggActionPerformed(evt);
            }
        });

        txt_DPI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_DPIActionPerformed(evt);
            }
        });

        lbl_DPI.setText("DPI:");

        btnbuscar.setText("BUSCAR");
        btnbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbuscarActionPerformed(evt);
            }
        });

        btn_UPDATE.setText("ACTUALIZAR");
        btn_UPDATE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_UPDATEActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbl_YEAR)
                        .addGap(29, 29, 29)
                        .addComponent(txt_YEAR, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(lbl_Welcome))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_close)
                        .addGap(18, 18, 18)
                        .addComponent(btn_agg)
                        .addGap(18, 18, 18)
                        .addComponent(btnbuscar)
                        .addGap(18, 18, 18)
                        .addComponent(btn_UPDATE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lbl_ID)
                            .addGap(46, 46, 46)
                            .addComponent(txt_ID, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbl_NOMBRE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txt_NOMBRE, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbl_NIT)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txt_NIT, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbl_DPI)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txt_DPI, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(lbl_Welcome)
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_ID)
                    .addComponent(txt_ID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_NOMBRE)
                    .addComponent(txt_NOMBRE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_NIT)
                    .addComponent(txt_NIT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_DPI)
                    .addComponent(txt_DPI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_YEAR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_YEAR))
                .addGap(84, 84, 84)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_close)
                    .addComponent(btn_agg)
                    .addComponent(btnbuscar)
                    .addComponent(btn_UPDATE))
                .addGap(40, 40, 40))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_IDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_IDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_IDActionPerformed

    private void txt_NOMBREActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_NOMBREActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_NOMBREActionPerformed

    private void txt_NITActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_NITActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_NITActionPerformed

    private void txt_YEARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_YEARActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_YEARActionPerformed

    private void btn_closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_closeActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_btn_closeActionPerformed

    private void btn_aggActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_aggActionPerformed
        int DIRECTOR_ID = Integer.parseInt(txt_ID.getText());
        String NOMBRE =txt_NOMBRE.getText();
        String DPI =txt_DPI.getText();
        String NIT =txt_NIT.getText();
        String FECHA_NACIMIENTO = txt_YEAR.getText();
         DT .SaveData (DIRECTOR_ID, NOMBRE, DPI, NIT, FECHA_NACIMIENTO);       
        JOptionPane.showMessageDialog(null, "Fue agregado exitosamente :D");
    }//GEN-LAST:event_btn_aggActionPerformed

    private void txt_DPIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_DPIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_DPIActionPerformed

    private void btnbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbuscarActionPerformed
        if(this.txt_ID.getText()!=null){
            //instancia de coneccion
            parcial_progra2.Conexion con = new parcial_progra2.Conexion();
            try {
                //consulta pa ver
                ResultSet rs = con.getConection().createStatement().executeQuery("select * from peliculas.director where DIRECTOR_ID="+this.txt_ID.getText());
                //recorrido
                if(rs.next()){

                    this.txt_ID.setEnabled(false);

                    this.txt_NOMBRE.setText(rs.getString(2));
                    this.txt_DPI.setText(rs.getString(3));
                    this.txt_NIT.setText(rs.getString(4));
                    this.txt_YEAR.setText(rs.getString(5));
                    }else{

                    JOptionPane.showConfirmDialog(null,"no se encontró  :c");
                }
            } catch (Exception ex) {
                JOptionPane.showConfirmDialog(null,ex);
            }
        }else{
            JOptionPane.showMessageDialog(null,"ERROR");
        }
    }//GEN-LAST:event_btnbuscarActionPerformed

    private void btn_UPDATEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_UPDATEActionPerformed
        DT.modData(Integer.parseInt(txt_ID.getText()),this.txt_NOMBRE.getText(),txt_DPI.getText(),txt_NIT.getText(),txt_YEAR.getText());

        JOptionPane.showMessageDialog(null, "Fue modificado exitosamente :D");
        this.txt_ID.setEnabled(true);
    }//GEN-LAST:event_btn_UPDATEActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Director.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Director.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Director.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Director.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Director().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_UPDATE;
    private javax.swing.JButton btn_agg;
    private javax.swing.JButton btn_close;
    private javax.swing.JButton btnbuscar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lbl_DPI;
    private javax.swing.JLabel lbl_ID;
    private javax.swing.JLabel lbl_NIT;
    private javax.swing.JLabel lbl_NOMBRE;
    private javax.swing.JLabel lbl_Welcome;
    private javax.swing.JLabel lbl_YEAR;
    private javax.swing.JTextField txt_DPI;
    private javax.swing.JTextField txt_ID;
    private javax.swing.JTextField txt_NIT;
    private javax.swing.JTextField txt_NOMBRE;
    private javax.swing.JTextField txt_YEAR;
    // End of variables declaration//GEN-END:variables

    private void SaveData(int DIRECTOR_ID, String NOMBRE, String DPI, String NIT, String FECHA_NACIMIENTO) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    private void modData(int parseInt, String text, String text0, String text1, String text2) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
